### ISSUE TITLE
Als gebruik wil ik kunnen doorverwijzen vanuit een component

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#12]
_Gegevens kunnen verwijzingen bevatten_

**Taken**
- [x] Onder #7 deze verwijzingen en mogelijkheid daartoe opnemen in de dataset. 
- [x] Bij de componenten detailpagina een plaats voor verwijzingen opnemen

**Acceptatiecriteria**
- [x] Als gebruiker wil ik op de componenten detailpagina doorverwijzingen kunnen zien en deze openen
- [x] De doorverwijzingen openen in een nieuw tabblad

**Comment by vwmvanbeek** [comment]
Github of Gitlab url opnemen?

**Comment by matthiasoliveiro** [comment]
Eens Github een github link

**Comment by rubenvdlinde** [comment]
In het huidige design is hiervoor ook al een plek opgenomen -> 
![image](https://user-images.githubusercontent.com/4021899/181500624-91b2ac6c-7b93-47ba-a219-452dfbec8c02.png)

**Comment by rjzondervan** [comment]
Deze is afhankelijk van #181

**Comment by rubenvdlinde** [comment]
- Dit wordt nu afgedekt onder downloads en onder de bollenplaat/card verwijzingen
