### ISSUE TITLE
Als gebruiker wil ik componenten en gegevens kunnen groeperen

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#14]
_Gegevens kunnen worden gegroepeerd_

**Taken**
- [x] Onder #7 deze groeperingen opnemen in de dataset. 
- [x] Bij de componenten detailpagina een plaats voor groepen opnemen zoals [afhankelijkheid]
- [x] Op de componenten overzicht pagina de mogelijkheid opnemen om alleen componenten van een bepaalde groep te tonen #123

**Comment by RonaldvCortenberghe** [comment]
De taken Onder https://github.com/OpenCatalogi/.github/issues/7 deze groeperingen opnemen in de dataset.
 Bij de componenten detailpagina een plaats voor groepen opnemen zie 
worden in sprint 2
Op de componenten overzicht pagina de mogelijkheid opnemen om alleen componenten van een bepaalde groep te tonen moet eigen userstory worden

**Comment by RonaldvCortenberghe** [comment]
Op de componenten overzicht pagina de mogelijkheid opnemen om alleen componenten van een bepaalde groep te tonen moet eigen userstory worden is user story #123 geworden

**Comment by lencodes** [comment]
> * Onder [Als gebruiker wil ik de gegevens kunnen Metadateren #7](https://github.com/OpenCatalogi/.github/issues/7) deze groeperingen opnemen in de dataset.

@RonaldvCortenberghe het is voor ons hier niet duidelijk om welke groepen het gaat, we hebben in #10 gekeken, hier lijken echter geen groepen gedefinieerd te worden, maar enkel velden. Zou je de groepen iets kunnen verduidelijken voor ons?

**Comment by rubenvdlinde** [comment]
@lencodes het gaat hier hellemaal niet om groepen maar om groeperen, het inzichtelijk maken van onderlinge verbanden tussen componenten. Dus bijvoorbeeld dit component maakt gebruikt van componenten a,b,c etc en word gebruikt door d,e,f. Bevat schema's 1,2,3 etc.

Het gaat hier dus feitelijk om het invullen van de tabbladen bij componenten.

**Comment by RonaldvCortenberghe** [comment]
done
