### ISSUE TITLE
[feature]: Als gebruiker wil ik admin pagina's

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#255]
### What is the goal of your request? Why should we do this?

Zodat ik mijn catalogus kan beheren

### The acceptance criteria of the feature

- [ ] Als gebruiker wil ik een admin scherm voor sources
- [ ] Als gebruiker wil ik een admin scherm voor actions
- [ ] Als gebruiker wil ik een admin scherm voor users
- [ ] Als gebruiker wil ik een admin scherm voor components
- [ ] Als gebruiker wil ik een admin scherm voor catalogi

### Project Location

Somewhere else (please specify in the description!)

**Comment by RonaldvCortenberghe** [comment]
Ik zal dit even met Ruben doornemen
