### ISSUE TITLE
Als team wil ik dat OpenCatalogi herbruikbaar is voor ander organisaties

### ISSUE THREAD

**Issue by rubenvdlinde** [OpenCatalogi/.github#28]
Zodat andere organisaties er ook hergebruik van gaan maken. Dat betekent dat er binnen het project aandacht en ruimte moet zijn voor zaken die niet in het directe belang zijn van Rotterdam. 

Taken

- [ ] Als team wil ik een "Over" pagina  over open catalogi op opencatalogi (die onderdeel is  van de documentatie)
- [ ] Als team wil ik een "Installatie" pagina  over open catalogi op opencatalogi (die onderdeel is  van de documentatie)
- [ ] Als team wil ik een "Gebruik" pagina  over open catalogi op opencatalogi (die onderdeel is  van de documentatie)
- [ ] Als team wil ik een "API" pagina  over open catalogi op opencatalogi (die onderdeel is  van de documentatie)
- [ ] #102 

Acceptatie  criteria

- [ ] Als externe organisatie kan ik OpenCatalogi  configureren en installeren op mijn eigen kubernetes omgeving (te testen door Rotterdam zelf de acceptatie omgeving te laten inrichten)

**Comment by rubenvdlinde** [comment]
Voorstel voor de aanpak:

Idealiter is een project zelf  documenterend, ofwel als gebruiker verwacht ik op opencatalogi.nl alle te kunnen vinden op opencatalogi.nl om zelf met opencatalogi aan de slag te kunnen. Vanuit deze context heb ik ook een review uitgevoerd op #19,, relevante punten daaruit  voor dit issue zijn:

- Documentatie pagina
- Goed doorlinken naar github vanaf de hoofdpagina

De documentatie pagina zou ik graag gaan vullen met  informatie vanuit read the docs (wat dan weer suggereert dat we ook voor opencatalogi een readthe docs gaan bijhouden). Voordeel hiervan is dan natuurlijk weer dat we de docmentatie  kunnen bijhouden als markdown files binnen het project.  En dat we de <infoicon> -- > <readthedocs modal> route kunnen gebruiken om in de primaire interface informatie weer te geven uit de readthedocs.

**Comment by MWest2020** [comment]
wordt meegenomen in #335 & #336
