### ISSUE TITLE
Visualisatie over de 5 lagen (detailpagina)

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#54]
"User Story  
* *Als:* APM 
* *Wil ik:* een visualisatie van componenten en hun onderlinge relaties over de 5-lagen heen 
* *Zodat ik:* van een component kan zien welke onder en bovenliggende componenten nodig zijn of gebruikt worden 

Beschrijving 

Dus als ik OpenCatalogi neemt, zou het in een overzicht helder moeten zijn welke api's bij OpenCatalogi beschikbaar zijn (en welke datamodel daarmee gemoeid zijn)

Deze story beschrijft ....... 

**Tasks**
- [ ] Uitzoeken hoe dependsOn in elkaar zit

**Geblokkeerd door:**
- [x] #140 

**Acceptatiecriteria:**

- [x] Als gebruiker wil ik de component weergave bij zoeken kunnen plotten op 5 lagen `FE: 13`
- [ ] Als gebruiker wil ik bij applicaties zien welke componenten ze gebruiken, opgedeeld in 5 lagen (bollen weergaven; zie inschatting onderstaande criteria)
- [ ] Als gebruiker wil ik bij componenten zien in welke applicaties ze worden gebruikt (bollen weergaven) `FE: 20`
- [ ] Als een component afhankelijk is van andere componenten wil ik dit op de component detail pagina zien onder afhankelijkheden `FE: 3`

**Comment by rubenvdlinde** [comment]
Dit vraag om drieweergaven, 

een component naar laag weergave als optie bij zoek resultaten. Alla componenten catalogus

![componentencatalogus_overzicht](https://user-images.githubusercontent.com/4021899/176591381-83760cdc-bc4c-406e-b56b-51b6347dce9c.png)

Een component detail pagina met daarop afhankelijkheden van ander componenten en applicaties waar het component deel van is. 
Een applicatie detail pagina die weergeeft hoe de applicatie is opgebouwd

De laatste twee kunnen we (grofweg) baseren op de developer.ovehreid applicatie detail pagina. 
![develeoperoverheid_api_detail](https://user-images.githubusercontent.com/4021899/176591647-0e94e9e6-5174-4f26-9d8f-6b6e7a0bbe21.png)

**Comment by lencodes** [comment]
> * [ ]  Als gebruiker wil ik bij applicaties zien welke componenten ze gebruiken, opgedeeld in 5 lagen (bollen weergaven; zie inschatting onderstaande criteria)
> * [ ]  Als gebruiker wil ik bij componenten zien in welke applicaties ze worden gebruikt (bollen weergaven) `FE: 20`

We gaan nu uit van de bollenplaat voor deze acceptatiecriterea. Verdere visualisaties staan in sprint 3 planned.

**Comment by bbrands02** [comment]
Het filter voor de lagen is nl.commonground.layerType en dependencies zijn te zien onder dependsOn.

**Comment by stephanieweerdenburg** [comment]
We splitsen deze op, acceptatiecriteria 1 (Als gebruiker wil ik de component weergave bij zoeken kunnen plotten op 5 lagen) en 4 ( Als een component afhankelijk is van andere componenten wil ik dit op de component detail pagina zien onder afhankelijkhede) pakken we op in sprint 1.

Acceptatiecriteria 2 en 3 verschuiven naar sprint 3, tenzij er in sprint 1 hier al tijd voor is. 
Als gebruiker wil ik bij applicaties zien welke componenten ze gebruiken, opgedeeld in 5 lagen (bollen weergaven; zie inschatting onderstaande criteria)
Als gebruiker wil ik bij componenten zien in welke applicaties ze worden gebruikt (bollen weergaven))

**Comment by lencodes** [comment]
@bbrands02 het gaat hier effectief nog om onderstaand acceptatiecriteria:

- [ ] Als een component afhankelijk is van andere componenten wil ik dit op de component detail pagina zien onder afhankelijkheden

De backend geeft in `.embedded` een `dependsOn` object mee, hier zitten echter enkel wat `UUID` values in waar we in de frontend (nog) niks mee kunnen.

Zou jij hier naar kunnen kijken wat de mogelijkheden zijn en deze klaarzetten in de backend?

**Comment by lencodes** [comment]
Meer informatie te vinden in #140.
