### ISSUE TITLE
Visualisatie per laag

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#56]
"User Story  
* *Als:* APM 
* *Wil ik:* per laag (van het 5-laagsmodel) een inzicht krijgen van wat er beschikbaar is 
* *Zodat ik:* alle api's kan bekijken of alle datamodellen 

Beschrijving 

Deze story beschrijft ....... 

**User stories**

- [x] #96
- [x] #100
- [x] #99
- [x] #98
- [x] #97

**Acceptatiecriteria:**

- [ ] Als developer wil ik een component dat ik op diverse plaatsen (zoekpagina, component detail pagina, applicatie detail pagina) kan gebruiken om weergaven van het 5 laags model te tonen
- [ ] Als gebruiker wil ik per laag een bij die laag passende weergeven
- [ ] Als gebruiker wil ik per laag een bij die laag passende aanvlieg route
- [ ] Als gebruik wil ik op de landings pagina de bij mij passende route kiezen

**Comment by rubenvdlinde** [comment]
Volgens mij word de functionele wens van dit issue afgedekt door #54

**Comment by rubenvdlinde** [comment]
Voorbeeld bij e huidige componenten catalogus 

![componentencatalogus_overzicht](https://user-images.githubusercontent.com/4021899/176591998-d711bfa1-c5b1-4226-8e0c-f4406123c3eb.png)

**Comment by JeroenGRotterdam** [comment]
Bron:https://www.gemmaonline.nl/index.php/Bestand:GemeentelijkGegevenslandschap.png
