### ISSUE TITLE
Als componenteigenaar wil ik CG componenten, modellen en documentatie kunnen publiceren , zodat ik met de beschikbaarstelling voor hergebruik een waardevolle bijdrage lever aan de CG Community.

### ISSUE THREAD

**Issue by matthiasoliveiro** [OpenCatalogi/.github#85]
"Als componenteigenaar wil ik CG componenten, modellen en documentatie kunnen publiceren , zodat ik met de beschikbaarstelling voor hergebruik een waardevolle bijdrage lever aan de CG Community. 

Alle informatie uit de individuele OpenCatalogi kan worden gepubliceerd voor gebruik door andere deelnemers en het totaaloverzicht.

Het is mogelijk door een geautoriseerd persoon binnen een organisatiee om te onderwerpen (componenten, modelen, etc) te kunnen publiceren namens dezelfde organisatie op Opencatalogi. Daarbij kan deze organisatie een doelgroep kiezen (Intern / specifieke deelnemende organisaties/ Publiek). 

**User stories**

- [ ] #66 
- [ ] #67
- [x] #69 
- [ ] #62

**Acceptatie criteria**:
- [ ] Doelgroep kunnen bepalen voor publiceren per onderwerp: eigen organisaties, specifieke organisaties (intern versus extern) , publiek.
- [ ] Publiceren is alleen mogelijk door daartoe geautoriseerde personen
- [ ] Publicaties zijn per onderwerp (componenten, modelen, etc)

**Comment by rubenvdlinde** [comment]
- Doelgroep is de design week besproken, we kennen er maar twee. Intern en Extern (wel of niet delen)
- Publicatie op een openbare website wil zeggen op open catalogi voor niet ingelogde gebruikers
- Hier sluit wel autorisatie het project in.

**Comment by MWest2020** [comment]
Wordt meegenomen in https://github.com/OpenCatalogi/.github/issues/358
